# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ELtest <- function(x, c, lhs, rhs, threshold, maxit = 1e4L, abstol = 1e-8) {
    .Call(`_elgbd_ELtest`, x, c, lhs, rhs, threshold, maxit, abstol)
}

pairwise <- function(x, c, control = 0L, k = 1L, level = 0.05, interval = TRUE, method = "AMC", B = 1e4L, nthread = 1L, progress = TRUE, threshold = 50, maxit = 1e4L, abstol = 1e-8) {
    .Call(`_elgbd_pairwise`, x, c, control, k, level, interval, method, B, nthread, progress, threshold, maxit, abstol)
}

get_max_threads <- function() {
    .Call(`_elgbd_get_max_threads`)
}

